// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatClient interface {
	ConnectChat(ctx context.Context, in *Room, opts ...grpc.CallOption) (*Client, error)
	GetMessages(ctx context.Context, in *Client, opts ...grpc.CallOption) (Chat_GetMessagesClient, error)
	SendMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type chatClient struct {
	cc grpc.ClientConnInterface
}

func NewChatClient(cc grpc.ClientConnInterface) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) ConnectChat(ctx context.Context, in *Room, opts ...grpc.CallOption) (*Client, error) {
	out := new(Client)
	err := c.cc.Invoke(ctx, "/pb.Chat/ConnectChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) GetMessages(ctx context.Context, in *Client, opts ...grpc.CallOption) (Chat_GetMessagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &Chat_ServiceDesc.Streams[0], "/pb.Chat/GetMessages", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatGetMessagesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Chat_GetMessagesClient interface {
	Recv() (*MessageResponse, error)
	grpc.ClientStream
}

type chatGetMessagesClient struct {
	grpc.ClientStream
}

func (x *chatGetMessagesClient) Recv() (*MessageResponse, error) {
	m := new(MessageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatClient) SendMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.Chat/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServer is the server API for Chat service.
// All implementations must embed UnimplementedChatServer
// for forward compatibility
type ChatServer interface {
	ConnectChat(context.Context, *Room) (*Client, error)
	GetMessages(*Client, Chat_GetMessagesServer) error
	SendMessage(context.Context, *MessageRequest) (*empty.Empty, error)
	mustEmbedUnimplementedChatServer()
}

// UnimplementedChatServer must be embedded to have forward compatible implementations.
type UnimplementedChatServer struct {
}

func (UnimplementedChatServer) ConnectChat(context.Context, *Room) (*Client, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectChat not implemented")
}
func (UnimplementedChatServer) GetMessages(*Client, Chat_GetMessagesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetMessages not implemented")
}
func (UnimplementedChatServer) SendMessage(context.Context, *MessageRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedChatServer) mustEmbedUnimplementedChatServer() {}

// UnsafeChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServer will
// result in compilation errors.
type UnsafeChatServer interface {
	mustEmbedUnimplementedChatServer()
}

func RegisterChatServer(s grpc.ServiceRegistrar, srv ChatServer) {
	s.RegisterService(&Chat_ServiceDesc, srv)
}

func _Chat_ConnectChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Room)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).ConnectChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Chat/ConnectChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).ConnectChat(ctx, req.(*Room))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_GetMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Client)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServer).GetMessages(m, &chatGetMessagesServer{stream})
}

type Chat_GetMessagesServer interface {
	Send(*MessageResponse) error
	grpc.ServerStream
}

type chatGetMessagesServer struct {
	grpc.ServerStream
}

func (x *chatGetMessagesServer) Send(m *MessageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Chat_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Chat/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).SendMessage(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Chat_ServiceDesc is the grpc.ServiceDesc for Chat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConnectChat",
			Handler:    _Chat_ConnectChat_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _Chat_SendMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetMessages",
			Handler:       _Chat_GetMessages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services.proto",
}

// ImageClient is the client API for Image service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageClient interface {
	GetImage(ctx context.Context, in *Room, opts ...grpc.CallOption) (Image_GetImageClient, error)
	GetWord(ctx context.Context, in *Room, opts ...grpc.CallOption) (Image_GetWordClient, error)
	GetCountdown(ctx context.Context, in *Room, opts ...grpc.CallOption) (Image_GetCountdownClient, error)
}

type imageClient struct {
	cc grpc.ClientConnInterface
}

func NewImageClient(cc grpc.ClientConnInterface) ImageClient {
	return &imageClient{cc}
}

func (c *imageClient) GetImage(ctx context.Context, in *Room, opts ...grpc.CallOption) (Image_GetImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &Image_ServiceDesc.Streams[0], "/pb.Image/GetImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &imageGetImageClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Image_GetImageClient interface {
	Recv() (*ImageResponse, error)
	grpc.ClientStream
}

type imageGetImageClient struct {
	grpc.ClientStream
}

func (x *imageGetImageClient) Recv() (*ImageResponse, error) {
	m := new(ImageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *imageClient) GetWord(ctx context.Context, in *Room, opts ...grpc.CallOption) (Image_GetWordClient, error) {
	stream, err := c.cc.NewStream(ctx, &Image_ServiceDesc.Streams[1], "/pb.Image/GetWord", opts...)
	if err != nil {
		return nil, err
	}
	x := &imageGetWordClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Image_GetWordClient interface {
	Recv() (*WordResponse, error)
	grpc.ClientStream
}

type imageGetWordClient struct {
	grpc.ClientStream
}

func (x *imageGetWordClient) Recv() (*WordResponse, error) {
	m := new(WordResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *imageClient) GetCountdown(ctx context.Context, in *Room, opts ...grpc.CallOption) (Image_GetCountdownClient, error) {
	stream, err := c.cc.NewStream(ctx, &Image_ServiceDesc.Streams[2], "/pb.Image/GetCountdown", opts...)
	if err != nil {
		return nil, err
	}
	x := &imageGetCountdownClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Image_GetCountdownClient interface {
	Recv() (*CountdownResponse, error)
	grpc.ClientStream
}

type imageGetCountdownClient struct {
	grpc.ClientStream
}

func (x *imageGetCountdownClient) Recv() (*CountdownResponse, error) {
	m := new(CountdownResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ImageServer is the server API for Image service.
// All implementations must embed UnimplementedImageServer
// for forward compatibility
type ImageServer interface {
	GetImage(*Room, Image_GetImageServer) error
	GetWord(*Room, Image_GetWordServer) error
	GetCountdown(*Room, Image_GetCountdownServer) error
	mustEmbedUnimplementedImageServer()
}

// UnimplementedImageServer must be embedded to have forward compatible implementations.
type UnimplementedImageServer struct {
}

func (UnimplementedImageServer) GetImage(*Room, Image_GetImageServer) error {
	return status.Errorf(codes.Unimplemented, "method GetImage not implemented")
}
func (UnimplementedImageServer) GetWord(*Room, Image_GetWordServer) error {
	return status.Errorf(codes.Unimplemented, "method GetWord not implemented")
}
func (UnimplementedImageServer) GetCountdown(*Room, Image_GetCountdownServer) error {
	return status.Errorf(codes.Unimplemented, "method GetCountdown not implemented")
}
func (UnimplementedImageServer) mustEmbedUnimplementedImageServer() {}

// UnsafeImageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageServer will
// result in compilation errors.
type UnsafeImageServer interface {
	mustEmbedUnimplementedImageServer()
}

func RegisterImageServer(s grpc.ServiceRegistrar, srv ImageServer) {
	s.RegisterService(&Image_ServiceDesc, srv)
}

func _Image_GetImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Room)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ImageServer).GetImage(m, &imageGetImageServer{stream})
}

type Image_GetImageServer interface {
	Send(*ImageResponse) error
	grpc.ServerStream
}

type imageGetImageServer struct {
	grpc.ServerStream
}

func (x *imageGetImageServer) Send(m *ImageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Image_GetWord_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Room)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ImageServer).GetWord(m, &imageGetWordServer{stream})
}

type Image_GetWordServer interface {
	Send(*WordResponse) error
	grpc.ServerStream
}

type imageGetWordServer struct {
	grpc.ServerStream
}

func (x *imageGetWordServer) Send(m *WordResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Image_GetCountdown_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Room)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ImageServer).GetCountdown(m, &imageGetCountdownServer{stream})
}

type Image_GetCountdownServer interface {
	Send(*CountdownResponse) error
	grpc.ServerStream
}

type imageGetCountdownServer struct {
	grpc.ServerStream
}

func (x *imageGetCountdownServer) Send(m *CountdownResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Image_ServiceDesc is the grpc.ServiceDesc for Image service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Image_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Image",
	HandlerType: (*ImageServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetImage",
			Handler:       _Image_GetImage_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetWord",
			Handler:       _Image_GetWord_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetCountdown",
			Handler:       _Image_GetCountdown_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services.proto",
}
